// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['main']['ChatBridge']['Cancel'](arg1);
}

export function OpenAI(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['ChatBridge']['OpenAI'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Start(arg1, arg2) {
  return window['go']['main']['ChatBridge']['Start'](arg1, arg2);
}
