// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close(arg1) {
  return window['go']['main']['SSHBridge']['Close'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['SSHBridge']['Connect'](arg1);
}

export function CreateClient(arg1) {
  return window['go']['main']['SSHBridge']['CreateClient'](arg1);
}

export function InitWithPasswd(arg1, arg2, arg3, arg4) {
  return window['go']['main']['SSHBridge']['InitWithPasswd'](arg1, arg2, arg3, arg4);
}

export function InitWithPem(arg1, arg2, arg3, arg4) {
  return window['go']['main']['SSHBridge']['InitWithPem'](arg1, arg2, arg3, arg4);
}

export function KeyDelete(arg1) {
  return window['go']['main']['SSHBridge']['KeyDelete'](arg1);
}

export function KeyGet(arg1) {
  return window['go']['main']['SSHBridge']['KeyGet'](arg1);
}

export function KeyPut(arg1, arg2) {
  return window['go']['main']['SSHBridge']['KeyPut'](arg1, arg2);
}

export function ListForwards(arg1) {
  return window['go']['main']['SSHBridge']['ListForwards'](arg1);
}

export function Resize(arg1, arg2, arg3) {
  return window['go']['main']['SSHBridge']['Resize'](arg1, arg2, arg3);
}

export function SFTPDownload(arg1, arg2) {
  return window['go']['main']['SSHBridge']['SFTPDownload'](arg1, arg2);
}

export function SFTPList(arg1, arg2) {
  return window['go']['main']['SSHBridge']['SFTPList'](arg1, arg2);
}

export function SFTPResumeUpload(arg1, arg2, arg3) {
  return window['go']['main']['SSHBridge']['SFTPResumeUpload'](arg1, arg2, arg3);
}

export function SFTPUpload(arg1, arg2, arg3) {
  return window['go']['main']['SSHBridge']['SFTPUpload'](arg1, arg2, arg3);
}

export function Send(arg1, arg2) {
  return window['go']['main']['SSHBridge']['Send'](arg1, arg2);
}

export function SetProxy(arg1, arg2) {
  return window['go']['main']['SSHBridge']['SetProxy'](arg1, arg2);
}

export function StartDynamicForward(arg1, arg2) {
  return window['go']['main']['SSHBridge']['StartDynamicForward'](arg1, arg2);
}

export function StartLocalForward(arg1, arg2, arg3) {
  return window['go']['main']['SSHBridge']['StartLocalForward'](arg1, arg2, arg3);
}

export function StartRemoteForward(arg1, arg2, arg3) {
  return window['go']['main']['SSHBridge']['StartRemoteForward'](arg1, arg2, arg3);
}

export function StopAllForwards(arg1) {
  return window['go']['main']['SSHBridge']['StopAllForwards'](arg1);
}

export function StopForward(arg1, arg2) {
  return window['go']['main']['SSHBridge']['StopForward'](arg1, arg2);
}

export function Write(arg1, arg2) {
  return window['go']['main']['SSHBridge']['Write'](arg1, arg2);
}
