// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Close(arg1:string):Promise<void>;

export function Connect(arg1:string):Promise<string>;

export function CreateClient(arg1:string):Promise<string>;

export function InitWithPasswd(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function InitWithPem(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function KeyDelete(arg1:string):Promise<string>;

export function KeyGet(arg1:string):Promise<string>;

export function KeyPut(arg1:string,arg2:string):Promise<string>;

export function ListForwards(arg1:string):Promise<string>;

export function Resize(arg1:string,arg2:number,arg3:number):Promise<string>;

export function SFTPDownload(arg1:string,arg2:string):Promise<main.SFTPDownloadResult>;

export function SFTPList(arg1:string,arg2:string):Promise<main.SFTPListResult>;

export function SFTPResumeUpload(arg1:string,arg2:string,arg3:Array<number>):Promise<string>;

export function SFTPUpload(arg1:string,arg2:string,arg3:Array<number>):Promise<string>;

export function Send(arg1:string,arg2:string):Promise<string>;

export function SetProxy(arg1:string,arg2:string):Promise<string>;

export function StartDynamicForward(arg1:string,arg2:string):Promise<string>;

export function StartLocalForward(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartRemoteForward(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StopAllForwards(arg1:string):Promise<string>;

export function StopForward(arg1:string,arg2:string):Promise<string>;

export function Write(arg1:string,arg2:string):Promise<string>;
